### PR TITLE
Cannot unpack non-iterable NoneType object

### PR DESCRIPTION
**Pull request by kuzhylol**
Bug fixing.

### CODE REVIEW

**Comment by Jayawardenepura** [comment]
Checking with Windows 10. Working for a long time.

**Comment by Y0r** [comment]
Just tested this on Fedora 35 Linux
Works well, should be merged into main after code review

**Comment by Y0r** [comment]
UPD:

Code looks fine, without critical changes that can be dangerous.

**Comment by Jayawardenepura** [comment]
Testing, still working good

**Pull request closed without merging**
